### ISSUE TITLE
Usage as Hasher in std::collections::HashMap?

### ISSUE THREAD

**Issue by phip1611** [RagnarGrootKoerkamp/PTRHash#7]
Hi there! I've come here because I found its usage in [0]. I'm not an expert
in hashing and hashmaps. I'm wondering if this perfect hashing algorithm can be
combined with `std::collections::HashMap` or `std::collections::BTreeMap`?

**My "request"/suggestion is**: Can you please add a few sentences in the README and documentation that classify this library against the standard library and the hashing implementations used there, including an example? This will help to understand people outside the loop what this actually is. :)

---

In the past days, I've jumped into the 1BRC challenge w/ Rust myself [1], that's how I ended up here (jup, I'm late to the party).

[0] https://github.com/RagnarGrootKoerkamp/1brc/blob/master/src/main.rs#L390
[1] https://github.com/phip1611/1brc-rust

**Comment by RagnarGrootKoerkamp** [comment]
Hey,

Perfect hashes don't really make sense to be used as hashers for a standard hashmap. Unlike normal hashes, constructing a perfect hash function requires knowing up front which keys you'll insert.
And given a perfect hash function, there is typically no need for the hashmap to store keys. But that makes it impossible to detect duplicate or unexpected keys.
So the typical case is to simply take the integer returned by the minimal perfect hash function and then to store an array that is directly indexed by this integer.

Hope this helps! I'll leave this open to update the readme later.

**Comment by phip1611** [comment]
Got it, thanks!

> And given a perfect hash function, there is typically no need for the hashmap to store keys.

Makes sense. But in case one knows beforehand that one only has `n` keys, I wonder if using the standard HashMap with the hashing algorithm provided by this crate can combine the performance benefit with a nice and well-known API/clean code?

**Comment by RagnarGrootKoerkamp** [comment]
Yes, that looks like how I'm using it. Just note that you could get away with not storing the `name` of the city in the `AggregateData` struct.
